<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ChiTietChuongTrinhDaoTao;

class ChiTietChuongTrinhDaoTaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ChiTietChuongTrinhDaoTao::insert([
            //Chuyên Ngành Lập Trình Website
            //Hk1
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 1,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 2,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 30,
                "so_tin_chi" => 1,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 3,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 4,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 5,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 6,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 7,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 8,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 9,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 10,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 90,
                "so_tin_chi" => 2,
            ],
            //HK2
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 11,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 12,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 30,
                "so_tin_chi" => 1,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 13,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 60,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 14,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 15,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 16,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 17,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 18,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 19,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 20,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK3
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 21,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 135,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 22,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 23,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 24,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 25,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 26,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 27,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 28,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 29,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 30,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK4
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 31,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 32,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 33,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 34,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 35,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 60,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 36,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 37,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 38,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK5
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 42,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 43,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 60,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 44,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 60,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 45,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 90,
                "so_tin_chi" => 6,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 46,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 90,
                "so_tin_chi" => 6,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 47,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 48,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            //HK6
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 58,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 59,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 60,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 61,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => null,
            ],


            //Chuyên Ngành Lập Trình di động
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 1, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 2, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 30, "so_tin_chi" => 1],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 3, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 30, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 4, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 5, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 6, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 7, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 8, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 9, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 10, "id_bo_mon" => null, "id_hoc_ky" => 1, "so_tiet" => 90, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 11, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 12, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 30, "so_tin_chi" => 1],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 13, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 60, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 14, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 15, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 16, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 17, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 18, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 19, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 20, "id_bo_mon" => null, "id_hoc_ky" => 2, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 21, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 135, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 22, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 23, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 24, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 30, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 25, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 26, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 27, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 28, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 29, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 30, "id_bo_mon" => null, "id_hoc_ky" => 3, "so_tiet" => 45, "so_tin_chi" => 2],
            //HK4
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 31, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 32, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 33, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 34, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 35, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 60, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 36, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 37, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 38, "id_bo_mon" => null, "id_hoc_ky" => 4, "so_tiet" => 45, "so_tin_chi" => 2],

            // HK5
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 42, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 45, "so_tin_chi" => 3],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 43, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 60, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 44, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 60, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 49, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 90, "so_tin_chi" => 6],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 50, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 75, "so_tin_chi" => 5],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 51, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 90, "so_tin_chi" => 6],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 48, "id_bo_mon" => null, "id_hoc_ky" => 5, "so_tiet" => 75, "so_tin_chi" => 5],

            // HK6
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 62, "id_bo_mon" => null, "id_hoc_ky" => 6, "so_tiet" => 30, "so_tin_chi" => 2],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 59, "id_bo_mon" => null, "id_hoc_ky" => 6, "so_tiet" => null, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 60, "id_bo_mon" => null, "id_hoc_ky" => 6, "so_tiet" => null, "so_tin_chi" => 4],
            ["id_chuong_trinh_dao_tao" => 2, "id_mon_hoc" => 61, "id_bo_mon" => null, "id_hoc_ky" => 6, "so_tiet" => null, "so_tin_chi" => null],


            //Chuyên Ngành Quản trị mạng
            //HK1
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 1,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 2,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 30,
                "so_tin_chi" => 1,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 3,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 4,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 5,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 6,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 7,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 8,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 9,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 10,
                "id_bo_mon" => null,
                "id_hoc_ky" => 1,
                "so_tiet" => 90,
                "so_tin_chi" => 2,
            ],
            //HK2
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 11,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 12,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 30,
                "so_tin_chi" => 1,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 13,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 60,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 14,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 15,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 16,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 17,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 18,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 19,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 20,
                "id_bo_mon" => null,
                "id_hoc_ky" => 2,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK3
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 21,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 135,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 22,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 23,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 24,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 25,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 26,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 27,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 28,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 29,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 30,
                "id_bo_mon" => null,
                "id_hoc_ky" => 3,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK4
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 31,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 32,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 33,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 39,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 40,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 41,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 90,
                "so_tin_chi" => 6,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 38,
                "id_bo_mon" => null,
                "id_hoc_ky" => 4,
                "so_tiet" => 45,
                "so_tin_chi" => 2,
            ],
            //HK5
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 34,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 52,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 53,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 54,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 55,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 45,
                "so_tin_chi" => 3,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 56,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 57,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 90,
                "so_tin_chi" => 6,
            ],
            [
                "id_chuong_trinh_dao_tao" => 1,
                "id_mon_hoc" => 48,
                "id_bo_mon" => null,
                "id_hoc_ky" => 5,
                "so_tiet" => 75,
                "so_tin_chi" => 5,
            ],
            //Hk6
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 63,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => 30,
                "so_tin_chi" => 2,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 59,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 60,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => 4,
            ],
            [
                "id_chuong_trinh_dao_tao" => 3,
                "id_mon_hoc" => 61,
                "id_bo_mon" => null,
                "id_hoc_ky" => 6,
                "so_tiet" => null,
                "so_tin_chi" => null,
            ],



        ]);
    }
}